version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:8080"
    restart: always
    # ★★★【追加箇所】★★★
    # サーバー上のファイルをコンテナ内で使えるようにする設定
    volumes:
      - /root/iina-key.json:/root/iina-key.json
    # アプリケーションに環境変数を渡す設定
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/iina-key.json
    # ★★★★★★★★★★★★★
