# Docker Composeファイルのバージョンを指定します
version: '3.8'

# ここに、起動するサービス（アプリケーション）を定義します
services:
  # 'app'という名前のサービスを定義します（名前は自由ですがappが一般的です）
  app:
    # Dockerfileがある場所を指定します。'.' は「このファイルと同じ階層」という意味です。
    build: .
    # サーバーのどのポートに来た通信を、コンテナのどのポートに繋ぐかを設定します。
    # 例: サーバーの80番ポートへのアクセスを、コンテナの8080番ポートへ転送
    ports:
      - "80:8080"
    # コンテナが何らかの理由で停止した際に、自動で再起動するように設定します
    restart: always
