# .github/workflows/deploy.yml (GanttLine方式への修正版)
# IINA PoC FrontendをLinodeサーバーに自動デプロイするためのワークフロー

name: Deploy IINA PoC to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # GanttLine方式: コミットメッセージに [to-linode] が含まれる場合のみ実行
    if: "contains(github.event.head_commit.message, '[to-linode]')"
    runs-on: ubuntu-latest

    steps:
      # ステップ1: リポジトリのコードをチェックアウトする
      - name: Checkout code
        uses: actions/checkout@v4

      # GanttLine方式: ステップ2 - SCPで全ファイルをサーバーにコピーする
      - name: Copy files to Linode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: root
          key: ${{ secrets.LINODE_SSH_KEY }}
          source: "."
          # IINA用のディレクトリを指定
          target: "/root/iina-poc"

      # GanttLine方式: ステップ3 - SSHでDocker Composeを再起動する
      - name: Restart with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: root
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            set -e
            cd /root/iina-poc
            docker-compose down
            docker-compose up -d --build